// Code generated by qtc from "state.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line state.qtpl:1
package templates

//line state.qtpl:1
import "fmt"

//line state.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line state.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line state.qtpl:2
func StreamGenerateState(qw422016 *qt422016.Writer, class *ClassDetails) {
//line state.qtpl:2
	qw422016.N().S(`
`)
//line state.qtpl:4
	sd := class.stateString()

//line state.qtpl:5
	qw422016.N().S(`
part of '`)
//line state.qtpl:6
	qw422016.E().S(class.Name)
//line state.qtpl:6
	qw422016.N().S(`_cubit.dart';

class `)
//line state.qtpl:8
	qw422016.E().S(class.Name)
//line state.qtpl:8
	qw422016.N().S(`State extends Equatable {
  const `)
//line state.qtpl:9
	qw422016.E().S(class.Name)
//line state.qtpl:9
	qw422016.N().S(`State(`)
//line state.qtpl:9
	qw422016.E().S(sd.State)
//line state.qtpl:9
	qw422016.N().S(`);

  `)
//line state.qtpl:11
	qw422016.E().S(sd.VarList)
//line state.qtpl:11
	qw422016.N().S(`
  @override
  List<Object> get props =>  [`)
//line state.qtpl:13
	qw422016.E().S(sd.PropsData)
//line state.qtpl:13
	qw422016.N().S(`];

  `)
//line state.qtpl:15
	qw422016.E().S(class.Name)
//line state.qtpl:15
	qw422016.N().S(`State copyWith(
    `)
//line state.qtpl:16
	qw422016.E().S(sd.CopyWithData)
//line state.qtpl:16
	qw422016.N().S(`
  }) {
    return `)
//line state.qtpl:18
	qw422016.E().S(class.Name)
//line state.qtpl:18
	qw422016.N().S(`State(
        `)
//line state.qtpl:19
	qw422016.E().S(sd.ChangeState)
//line state.qtpl:19
	qw422016.N().S(`
    );
  }
}

`)
//line state.qtpl:24
}

//line state.qtpl:24
func WriteGenerateState(qq422016 qtio422016.Writer, class *ClassDetails) {
//line state.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line state.qtpl:24
	StreamGenerateState(qw422016, class)
//line state.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line state.qtpl:24
}

//line state.qtpl:24
func GenerateState(class *ClassDetails) string {
//line state.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line state.qtpl:24
	WriteGenerateState(qb422016, class)
//line state.qtpl:24
	qs422016 := string(qb422016.B)
//line state.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line state.qtpl:24
	return qs422016
//line state.qtpl:24
}

//line state.qtpl:27
type StateData struct {
	State        string
	VarList      string
	CopyWithData string
	ChangeState  string
	PropsData    string
}

func (C *ClassDetails) stateString() *StateData {

	var stateStr = ""
	var varListStr = ""
	var copyWithData = ""
	var changeStateStr = ""
	var propsData = ""

	for _, variable := range C.Variables {
		stateStr += fmt.Sprintf("this.%s=%s,", variable.Name, variable.InitialValue)
		varListStr += fmt.Sprintf("final %s %s;\n", variable.Type, variable.Name)
		copyWithData += fmt.Sprintf("%s %s,\n", variable.Type, variable.Name)
		changeStateStr += fmt.Sprintf("%s : %s ?? this.%s,\n", variable.Name, variable.Name, variable.Name)
		propsData += fmt.Sprintf("%s,", variable.Name)
	}

	sd := &StateData{
		State:        fmt.Sprintf("{%s}", stateStr),
		VarList:      varListStr,
		CopyWithData: copyWithData,
		ChangeState:  changeStateStr,
		PropsData:    propsData,
	}
	return sd
}
